version: '3.1'

services:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      -3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  
  base:
    image: base:1
    restart: always
    depends_on:
      - mysql
    ports:
      -1233:80
